import type { City } from '@/lib/types/cities';

export const CAPITAL_CITIES: City[] = [
  {
    name: 'Abu Dhabi',
    country: { code: 'AE', name: 'United Arab Emirates' },
    latitude: 24.28,
    longitude: 54.22,
  },
  { name: 'Abuja', country: { code: 'NG', name: 'Nigeria' }, latitude: 9.05, longitude: 7.32 },
  { name: 'Accra', country: { code: 'GH', name: 'Ghana' }, latitude: 5.35, longitude: -0.06 },
  {
    name: 'Addis Ababa',
    country: { code: 'ET', name: 'Ethiopia' },
    latitude: 9.02,
    longitude: 38.42,
  },
  { name: 'Algiers', country: { code: 'DZ', name: 'Algeria' }, latitude: 36.42, longitude: 3.08 },
  { name: 'Amman', country: { code: 'JO', name: 'Jordan' }, latitude: 31.57, longitude: 35.52 },
  {
    name: 'Amsterdam',
    country: { code: 'NL', name: 'Netherlands' },
    latitude: 12.05,
    longitude: -69.0,
  },
  {
    name: 'Andorra la Vella',
    country: { code: 'AD', name: 'Andorra' },
    latitude: 42.31,
    longitude: 1.32,
  },
  { name: 'Ankara', country: { code: 'TR', name: 'Turkey' }, latitude: 39.57, longitude: 32.54 },
  {
    name: 'Antananarivo',
    country: { code: 'MG', name: 'Madagascar' },
    latitude: -18.55,
    longitude: 47.31,
  },
  { name: 'Apia', country: { code: 'WS', name: 'Samoa' }, latitude: -14.16, longitude: -170.43 },
  {
    name: 'Ashgabat',
    country: { code: 'TM', name: 'Turkmenistan' },
    latitude: 38.0,
    longitude: 57.5,
  },
  { name: 'Asmara', country: { code: 'ER', name: 'Eritrea' }, latitude: 15.19, longitude: 38.55 },
  { name: 'Astana', country: { code: 'KZ', name: 'Kazakhstan' }, latitude: 51.1, longitude: 71.3 },
  {
    name: 'Asuncion',
    country: { code: 'PY', name: 'Paraguay' },
    latitude: -25.1,
    longitude: -57.3,
  },
  { name: 'Athens', country: { code: 'GR', name: 'Greece' }, latitude: 37.58, longitude: 23.46 },
  { name: 'Baghdad', country: { code: 'IQ', name: 'Iraq' }, latitude: 33.2, longitude: 44.3 },
  { name: 'Baku', country: { code: 'AZ', name: 'Azerbaijan' }, latitude: 40.29, longitude: 49.56 },
  { name: 'Bamako', country: { code: 'ML', name: 'Mali' }, latitude: 12.34, longitude: -7.55 },
  {
    name: 'Bandar Seri Begawan',
    country: { code: 'BN', name: 'Brunei' },
    latitude: 4.52,
    longitude: 115.0,
  },
  {
    name: 'Bangkok',
    country: { code: 'TH', name: 'Thailand' },
    latitude: 13.45,
    longitude: 100.35,
  },
  {
    name: 'Bangui',
    country: { code: 'CF', name: 'Central African Republic' },
    latitude: 4.23,
    longitude: 18.35,
  },
  { name: 'Banjul', country: { code: 'GM', name: 'Gambia' }, latitude: 13.28, longitude: -16.4 },
  {
    name: 'Basseterre',
    country: { code: 'KN', name: 'Saint Kitts and Nevis' },
    latitude: 17.17,
    longitude: -62.43,
  },
  { name: 'Beijing', country: { code: 'CN', name: 'China' }, latitude: 39.55, longitude: 116.2 },
  { name: 'Beirut', country: { code: 'LB', name: 'Lebanon' }, latitude: 33.53, longitude: 35.31 },
  {
    name: 'Belfast',
    country: { code: 'GB', name: 'Northern Ireland' },
    latitude: 54.59,
    longitude: -5.93,
  },
  { name: 'Belgrade', country: { code: 'RS', name: 'Serbia' }, latitude: 44.81, longitude: 20.46 },
  { name: 'Belmopan', country: { code: 'BZ', name: 'Belize' }, latitude: 17.18, longitude: -88.3 },
  { name: 'Berlin', country: { code: 'DE', name: 'Germany' }, latitude: 52.3, longitude: 13.25 },
  { name: 'Bern', country: { code: 'CH', name: 'Switzerland' }, latitude: 46.57, longitude: 7.28 },
  {
    name: 'Bishkek',
    country: { code: 'KG', name: 'Kyrgyzstan' },
    latitude: 42.54,
    longitude: 74.46,
  },
  {
    name: 'Bissau',
    country: { code: 'GW', name: 'Guinea-Bissau' },
    latitude: 11.45,
    longitude: -15.45,
  },
  { name: 'Bogota', country: { code: 'CO', name: 'Colombia' }, latitude: 4.34, longitude: -74.0 },
  {
    name: 'Brasilia',
    country: { code: 'BR', name: 'Brazil' },
    latitude: -15.47,
    longitude: -47.55,
  },
  {
    name: 'Bratislava',
    country: { code: 'SK', name: 'Slovakia' },
    latitude: 48.1,
    longitude: 17.07,
  },
  {
    name: 'Brazzaville',
    country: { code: 'CG', name: 'Congo, Republic of the' },
    latitude: -4.09,
    longitude: 15.12,
  },
  {
    name: 'Bridgetown',
    country: { code: 'BB', name: 'Barbados' },
    latitude: 13.05,
    longitude: -59.3,
  },
  { name: 'Brussels', country: { code: 'BE', name: 'Belgium' }, latitude: 50.51, longitude: 4.21 },
  { name: 'Bucharest', country: { code: 'RO', name: 'Romania' }, latitude: 44.27, longitude: 26.1 },
  { name: 'Budapest', country: { code: 'HU', name: 'Hungary' }, latitude: 47.29, longitude: 19.05 },
  {
    name: 'Buenos Aires',
    country: { code: 'AR', name: 'Argentina' },
    latitude: -36.3,
    longitude: -60.0,
  },
  { name: 'Cairo', country: { code: 'EG', name: 'Egypt' }, latitude: 30.01, longitude: 31.14 },
  {
    name: 'Canberra',
    country: { code: 'AU', name: 'Australia' },
    latitude: -35.15,
    longitude: 149.08,
  },
  {
    name: 'Caracas',
    country: { code: 'VE', name: 'Venezuela' },
    latitude: 10.3,
    longitude: -66.55,
  },
  {
    name: 'Castries',
    country: { code: 'LC', name: 'Saint Lucia' },
    latitude: 14.02,
    longitude: -60.58,
  },
  { name: 'Chisinau', country: { code: 'MD', name: 'Moldova' }, latitude: 47.02, longitude: 28.5 },
  { name: 'Conakry', country: { code: 'GN', name: 'Guinea' }, latitude: 9.29, longitude: -13.49 },
  {
    name: 'Copenhagen',
    country: { code: 'DK', name: 'Denmark' },
    latitude: 55.41,
    longitude: 12.34,
  },
  { name: 'Dakar', country: { code: 'SN', name: 'Senegal' }, latitude: 14.34, longitude: -17.29 },
  { name: 'Damascus', country: { code: 'SY', name: 'Syria' }, latitude: 33.3, longitude: 36.18 },
  { name: 'Dhaka', country: { code: 'BD', name: 'Bangladesh' }, latitude: 23.43, longitude: 90.26 },
  { name: 'Dili', country: { code: 'TL', name: 'East Timor' }, latitude: -8.29, longitude: 125.34 },
  { name: 'Djibouti', country: { code: 'DJ', name: 'Djibouti' }, latitude: 11.08, longitude: 42.2 },
  { name: 'Dodoma', country: { code: 'TZ', name: 'Tanzania' }, latitude: -6.18, longitude: 35.74 },
  { name: 'Doha', country: { code: 'QA', name: 'Qatar' }, latitude: 25.15, longitude: 51.35 },
  { name: 'Dublin', country: { code: 'IE', name: 'Ireland' }, latitude: 53.21, longitude: -6.15 },
  {
    name: 'Dushanbe',
    country: { code: 'TJ', name: 'Tajikistan' },
    latitude: 38.33,
    longitude: 68.48,
  },
  {
    name: 'Edinburgh',
    country: { code: 'GB', name: 'Scotland' },
    latitude: 55.95,
    longitude: -3.18,
  },
  {
    name: 'Freetown',
    country: { code: 'SL', name: 'Sierra Leone' },
    latitude: 8.3,
    longitude: -13.17,
  },
  { name: 'Funafuti', country: { code: 'TV', name: 'Tuvalu' }, latitude: -8.31, longitude: 179.13 },
  {
    name: 'Gaborone',
    country: { code: 'BW', name: 'Botswana' },
    latitude: -24.45,
    longitude: 25.57,
  },
  { name: 'Georgetown', country: { code: 'GY', name: 'Guyana' }, latitude: 6.5, longitude: -58.12 },
  { name: 'Gitega', country: { code: 'BI', name: 'Burundi' }, latitude: -3.16, longitude: 29.18 },
  {
    name: 'Guatemala City',
    country: { code: 'GT', name: 'Guatemala' },
    latitude: 14.4,
    longitude: -90.22,
  },
  { name: 'Hanoi', country: { code: 'VN', name: 'Vietnam' }, latitude: 21.05, longitude: 105.55 },
  { name: 'Harare', country: { code: 'ZW', name: 'Zimbabwe' }, latitude: -17.43, longitude: 31.02 },
  { name: 'Havana', country: { code: 'CU', name: 'Cuba' }, latitude: 23.08, longitude: -82.22 },
  { name: 'Helsinki', country: { code: 'FI', name: 'Finland' }, latitude: 60.15, longitude: 25.03 },
  {
    name: 'Honiara',
    country: { code: 'SB', name: 'Solomon Islands' },
    latitude: -9.27,
    longitude: 159.57,
  },
  { name: 'Islamabad', country: { code: 'PK', name: 'Pakistan' }, latitude: 33.4, longitude: 73.1 },
  {
    name: 'Jakarta',
    country: { code: 'ID', name: 'Indonesia' },
    latitude: -6.09,
    longitude: 106.49,
  },
  {
    name: 'Jerusalem',
    country: { code: 'IL', name: 'Israel' },
    latitude: 31.71,
    longitude: -35.1,
  },
  { name: 'Juba', country: { code: 'SS', name: 'South Sudan' }, latitude: 4.85, longitude: 31.58 },
  {
    name: 'Kabul',
    country: { code: 'AF', name: 'Afghanistan' },
    latitude: 34.28,
    longitude: 69.11,
  },
  { name: 'Kampala', country: { code: 'UG', name: 'Uganda' }, latitude: 0.2, longitude: 32.3 },
  { name: 'Kathmandu', country: { code: 'NP', name: 'Nepal' }, latitude: 27.45, longitude: 85.2 },
  { name: 'Khartoum', country: { code: 'SD', name: 'Sudan' }, latitude: 15.31, longitude: 32.35 },
  { name: 'Kigali', country: { code: 'RW', name: 'Rwanda' }, latitude: -1.59, longitude: 30.04 },
  { name: 'Kingston', country: { code: 'JM', name: 'Jamaica' }, latitude: 18.0, longitude: -76.5 },
  {
    name: 'Kingstown',
    country: { code: 'VC', name: 'Saint Vincent and the Grenadines' },
    latitude: 13.1,
    longitude: -61.1,
  },
  {
    name: 'Kinshasa',
    country: { code: 'CD', name: 'Congo, Democratic Republic of the' },
    latitude: -4.2,
    longitude: 15.15,
  },
  {
    name: 'Kuala Lumpur',
    country: { code: 'MY', name: 'Malaysia' },
    latitude: 3.09,
    longitude: 101.41,
  },
  { name: 'Kuwait City', country: { code: 'KW', name: 'Kuwait' }, latitude: 29.3, longitude: 48.0 },
  {
    name: 'Kiev',
    country: { code: 'UA', name: 'Ukraine' },
    latitude: 50.3,
    longitude: 30.28,
  },
  { name: 'Sucre', country: { code: 'BO', name: 'Bolivia' }, latitude: -16.2, longitude: -68.1 },
  { name: 'Libreville', country: { code: 'GA', name: 'Gabon' }, latitude: 0.25, longitude: 9.26 },
  { name: 'Lilongwe', country: { code: 'MW', name: 'Malawi' }, latitude: -14.0, longitude: 33.48 },
  { name: 'Lima', country: { code: 'PE', name: 'Peru' }, latitude: -12.0, longitude: -77.0 },
  { name: 'Lisbon', country: { code: 'PT', name: 'Portugal' }, latitude: 38.42, longitude: -9.1 },
  {
    name: 'Ljubljana',
    country: { code: 'SI', name: 'Slovenia' },
    latitude: 46.04,
    longitude: 14.33,
  },
  { name: 'Lome', country: { code: 'TG', name: 'Togo' }, latitude: 6.09, longitude: 1.2 },
  {
    name: 'London',
    country: { code: 'GB', name: 'United Kingdom' },
    latitude: 51.36,
    longitude: -0.05,
  },
  { name: 'Luanda', country: { code: 'AO', name: 'Angola' }, latitude: -8.5, longitude: 13.15 },
  { name: 'Lusaka', country: { code: 'ZM', name: 'Zambia' }, latitude: -15.28, longitude: 28.16 },
  {
    name: 'Luxembourg',
    country: { code: 'LU', name: 'Luxembourg' },
    latitude: 49.37,
    longitude: 6.09,
  },
  { name: 'Madrid', country: { code: 'ES', name: 'Spain' }, latitude: 40.25, longitude: -3.45 },
  {
    name: 'Majuro',
    country: { code: 'MH', name: 'Marshall Islands' },
    latitude: 7.06,
    longitude: 171.26,
  },
  {
    name: 'Malabo',
    country: { code: 'GQ', name: 'Equatorial Guinea' },
    latitude: 3.45,
    longitude: 8.5,
  },
  { name: 'Male', country: { code: 'MV', name: 'Maldives' }, latitude: 4.0, longitude: 73.28 },
  {
    name: 'Managua',
    country: { code: 'NI', name: 'Nicaragua' },
    latitude: 12.06,
    longitude: -86.2,
  },
  { name: 'Manama', country: { code: 'BH', name: 'Bahrain' }, latitude: 26.1, longitude: 50.3 },
  {
    name: 'Manila',
    country: { code: 'PH', name: 'Philippines' },
    latitude: 14.4,
    longitude: 121.03,
  },
  {
    name: 'Maputo',
    country: { code: 'MZ', name: 'Mozambique' },
    latitude: -25.58,
    longitude: 32.32,
  },
  { name: 'Maseru', country: { code: 'LS', name: 'Lesotho' }, latitude: -29.18, longitude: 27.3 },
  {
    name: 'Melekeok',
    country: { code: 'PW', name: 'Palau' },
    latitude: 7.5004,
    longitude: 134.6243,
  },
  {
    name: 'Mexico City',
    country: { code: 'MX', name: 'Mexico' },
    latitude: 19.2,
    longitude: -99.1,
  },
  { name: 'Minsk', country: { code: 'BY', name: 'Belarus' }, latitude: 53.52, longitude: 27.3 },
  { name: 'Mogadishu', country: { code: 'SO', name: 'Somalia' }, latitude: 2.02, longitude: 45.25 },
  { name: 'Monaco', country: { code: 'MC', name: 'Monaco' }, latitude: 43.73, longitude: 7.42 },
  { name: 'Monrovia', country: { code: 'LR', name: 'Liberia' }, latitude: 6.18, longitude: -10.47 },
  {
    name: 'Montevideo',
    country: { code: 'UY', name: 'Uruguay' },
    latitude: -34.5,
    longitude: -56.11,
  },
  { name: 'Moroni', country: { code: 'KM', name: 'Comoros' }, latitude: -11.4, longitude: 43.16 },
  { name: 'Moscow', country: { code: 'RU', name: 'Russia' }, latitude: 55.45, longitude: 37.35 },
  { name: 'Muscat', country: { code: 'OM', name: 'Oman' }, latitude: 23.37, longitude: 58.36 },
  { name: 'Nairobi', country: { code: 'KE', name: 'Kenya' }, latitude: -1.17, longitude: 36.48 },
  { name: 'Nassau', country: { code: 'BS', name: 'Bahamas' }, latitude: 25.05, longitude: -77.2 },
  {
    name: 'Nay Pyi Taw',
    country: { code: 'MM', name: 'Myanmar' },
    latitude: 16.45,
    longitude: 96.2,
  },
  // eslint-disable-next-line prettier/prettier
  { name: "N'Djamena", country: { code: 'TD', name: 'Chad' }, latitude: 12.1, longitude: 14.59 },
  { name: 'New Delhi', country: { code: 'IN', name: 'India' }, latitude: 28.37, longitude: 77.13 },
  { name: 'Niamey', country: { code: 'NE', name: 'Niger' }, latitude: 13.27, longitude: 2.06 },
  {
    name: 'Nicosia',
    country: { code: 'CY', name: 'Cyprus' },
    latitude: 35.1,
    longitude: 33.25,
  },
  {
    name: 'Nouakchott',
    country: { code: 'MR', name: 'Mauritania' },
    latitude: -20.1,
    longitude: 57.3,
  },
  {
    // eslint-disable-next-line prettier/prettier
    name: "Nuku'alofa",
    country: { code: 'TO', name: 'Tonga' },
    latitude: -21.1,
    longitude: -174.0,
  },
  { name: 'Oslo', country: { code: 'NO', name: 'Norway' }, latitude: 59.55, longitude: 10.45 },
  { name: 'Ottawa', country: { code: 'CA', name: 'Canada' }, latitude: 45.27, longitude: -75.42 },
  {
    name: 'Ouagadougou',
    country: { code: 'BF', name: 'Burkina Faso' },
    latitude: 12.15,
    longitude: -1.3,
  },
  {
    name: 'Panama City',
    country: { code: 'PA', name: 'Panama' },
    latitude: 9.0,
    longitude: -79.25,
  },
  {
    name: 'Paramaribo',
    country: { code: 'SR', name: 'Suriname' },
    latitude: 5.5,
    longitude: -55.1,
  },
  { name: 'Paris', country: { code: 'FR', name: 'France' }, latitude: 48.5, longitude: 2.2 },
  {
    name: 'Phnom Penh',
    country: { code: 'KH', name: 'Cambodia' },
    latitude: 11.33,
    longitude: 104.55,
  },
  {
    name: 'Podgorica',
    country: { code: 'ME', name: 'Montenegro' },
    latitude: 42.43,
    longitude: 19.25,
  },
  {
    name: 'Port au Prince',
    country: { code: 'HT', name: 'Haiti' },
    latitude: 18.4,
    longitude: -72.2,
  },
  {
    name: 'Port Louis',
    country: { code: 'MU', name: 'Mauritius' },
    latitude: -20.16,
    longitude: 57.5,
  },
  {
    name: 'Port Moresby',
    country: { code: 'PG', name: 'Papua New Guinea' },
    latitude: -9.24,
    longitude: 147.08,
  },
  {
    name: 'Port of Spain',
    country: { code: 'TT', name: 'Trinidad and Tobago' },
    latitude: 10.66,
    longitude: -61.5,
  },
  {
    name: 'Port Vila',
    country: { code: 'VU', name: 'Vanuatu' },
    latitude: -17.45,
    longitude: 168.18,
  },
  { name: 'Porto Novo', country: { code: 'BJ', name: 'Benin' }, latitude: 6.23, longitude: 2.42 },
  {
    name: 'Prague',
    country: { code: 'CZ', name: 'Czech Republic' },
    latitude: 50.05,
    longitude: 14.22,
  },
  {
    name: 'Praia',
    country: { code: 'CV', name: 'Cape Verde' },
    latitude: 15.02,
    longitude: -23.34,
  },
  {
    name: 'Cape Town',
    country: { code: 'ZA', name: 'South Africa' },
    latitude: -25.44,
    longitude: 28.12,
  },
  {
    name: 'Pristina',
    country: { code: 'XK', name: 'Kosovo' },
    latitude: 42.66,
    longitude: 21.16,
  },
  {
    name: 'Pyongyang',
    country: { code: 'KP', name: 'North Korea' },
    latitude: 39.07,
    longitude: 125.81,
  },
  { name: 'Quito', country: { code: 'EC', name: 'Ecuador' }, latitude: -0.15, longitude: -78.35 },
  { name: 'Rabat', country: { code: 'MA', name: 'Morocco' }, latitude: 34.0, longitude: -6.85 },
  {
    name: 'Reykjavik',
    country: { code: 'IS', name: 'Iceland' },
    latitude: 64.1,
    longitude: -21.57,
  },
  { name: 'Riga', country: { code: 'LV', name: 'Latvia' }, latitude: 56.53, longitude: 24.08 },
  {
    name: 'Riyadh',
    country: { code: 'SA', name: 'Saudi Arabia' },
    latitude: 24.41,
    longitude: 46.42,
  },
  { name: 'Rome', country: { code: 'IT', name: 'Italy' }, latitude: 41.54, longitude: 12.29 },
  { name: 'Roseau', country: { code: 'DM', name: 'Dominica' }, latitude: 15.2, longitude: -61.24 },
  {
    name: 'Saint George',
    country: { code: 'GD', name: 'Grenada' },
    latitude: 32.38,
    longitude: -64.67,
  },
  {
    name: 'Saint John',
    country: { code: 'AG', name: 'Antigua and Barbuda' },
    latitude: 17.127,
    longitude: -61.846,
  },
  {
    name: 'San Jose',
    country: { code: 'CR', name: 'Costa Rica' },
    latitude: 9.55,
    longitude: -84.02,
  },
  {
    name: 'San Marino',
    country: { code: 'SM', name: 'San Marino' },
    latitude: 43.55,
    longitude: 12.3,
  },
  {
    name: 'San Salvador',
    country: { code: 'SV', name: 'El Salvador' },
    latitude: 13.4,
    longitude: -89.1,
  },
  { name: 'Sana', country: { code: 'YE', name: 'Yemen' }, latitude: 15.35, longitude: 44.2 },
  { name: 'Santiago', country: { code: 'CL', name: 'Chile' }, latitude: -33.24, longitude: -70.4 },
  {
    name: 'Santo Domingo',
    country: { code: 'DO', name: 'Dominican Republic' },
    latitude: 18.3,
    longitude: -69.59,
  },
  {
    name: 'Sao Tome',
    country: { code: 'ST', name: 'Sao Tome and Principe' },
    latitude: 0.1,
    longitude: 6.39,
  },
  {
    name: 'Sarajevo',
    country: { code: 'BA', name: 'Bosnia and Herzegovina' },
    latitude: 43.52,
    longitude: 18.26,
  },
  {
    name: 'Seoul',
    country: { code: 'KR', name: 'South Korea' },
    latitude: 37.31,
    longitude: 126.58,
  },
  {
    name: 'Singapore',
    country: { code: 'SG', name: 'Singapore' },
    latitude: 1.35,
    longitude: 103.81,
  },
  {
    name: 'Skopje',
    country: { code: 'MK', name: 'North Macedonia' },
    latitude: 41.99,
    longitude: 21.42,
  },
  { name: 'Sofia', country: { code: 'BG', name: 'Bulgaria' }, latitude: 42.45, longitude: 23.2 },
  {
    name: 'Sri Jayawardenapura Kotte',
    country: { code: 'LK', name: 'Sri Lanka' },
    latitude: 6.88,
    longitude: 79.91,
  },
  { name: 'Stockholm', country: { code: 'SE', name: 'Sweden' }, latitude: 59.2, longitude: 18.03 },
  { name: 'Suva', country: { code: 'FJ', name: 'Fiji' }, latitude: -18.06, longitude: 178.3 },
  {
    name: 'Taipei',
    country: { code: 'TW', name: 'Taiwan' },
    latitude: 25.03,
    longitude: 121.56,
  },
  { name: 'Tallinn', country: { code: 'EE', name: 'Estonia' }, latitude: 59.22, longitude: 24.48 },
  {
    name: 'Tarawa Atoll',
    country: { code: 'KI', name: 'Kiribati' },
    latitude: 1.3,
    longitude: 173.0,
  },
  {
    name: 'Tashkent',
    country: { code: 'UZ', name: 'Uzbekistan' },
    latitude: 41.2,
    longitude: 69.1,
  },
  { name: 'Tbilisi', country: { code: 'GE', name: 'Georgia' }, latitude: 41.43, longitude: 44.5 },
  {
    name: 'Tegucigalpa',
    country: { code: 'HN', name: 'Honduras' },
    latitude: 14.05,
    longitude: -87.14,
  },
  { name: 'Tehran', country: { code: 'IR', name: 'Iran' }, latitude: 35.44, longitude: 51.3 },
  { name: 'Thimphu', country: { code: 'BT', name: 'Bhutan' }, latitude: 27.31, longitude: 89.45 },
  { name: 'Tirana', country: { code: 'AL', name: 'Albania' }, latitude: 41.18, longitude: 19.49 },
  { name: 'Tokyo', country: { code: 'JP', name: 'Japan' }, latitude: 35.67, longitude: 139.65 },
  { name: 'Tripoli', country: { code: 'LY', name: 'Libya' }, latitude: 32.49, longitude: 13.07 },
  { name: 'Tunis', country: { code: 'TN', name: 'Tunisia' }, latitude: 36.5, longitude: 10.11 },
  {
    name: 'Ulaanbaatar',
    country: { code: 'MN', name: 'Mongolia' },
    latitude: 47.92,
    longitude: 106.91,
  },
  {
    name: 'Vaduz',
    country: { code: 'LI', name: 'Liechtenstein' },
    latitude: 47.08,
    longitude: 9.31,
  },
  { name: 'Valletta', country: { code: 'MT', name: 'Malta' }, latitude: 35.54, longitude: 14.31 },
  {
    name: 'Vatican City',
    country: { code: 'VA', name: 'Vatican City' },
    latitude: 41.9,
    longitude: 12.45,
  },
  { name: 'Vienna', country: { code: 'AT', name: 'Austria' }, latitude: 48.12, longitude: 16.22 },
  { name: 'Vientiane', country: { code: 'LA', name: 'Laos' }, latitude: 17.58, longitude: 102.36 },
  {
    name: 'Vilnius',
    country: { code: 'LT', name: 'Lithuania' },
    latitude: 54.38,
    longitude: 25.19,
  },
  { name: 'Warsaw', country: { code: 'PL', name: 'Poland' }, latitude: 52.13, longitude: 21.0 },
  {
    name: 'Washington D.C.',
    country: { code: 'US', name: 'United States' },
    latitude: 39.91,
    longitude: -77.02,
  },
  {
    name: 'Wellington',
    country: { code: 'NZ', name: 'New Zealand' },
    latitude: -41.19,
    longitude: 174.46,
  },
  {
    name: 'Windhoek',
    country: { code: 'NA', name: 'Namibia' },
    latitude: -22.35,
    longitude: 17.04,
  },
  {
    name: 'Yamoussoukro',
    // eslint-disable-next-line prettier/prettier
    country: { code: 'CI', name: "Côte d'Ivoire" },
    latitude: -6.49,
    longitude: -5.17,
  },
  { name: 'Yaounde', country: { code: 'CM', name: 'Cameroon' }, latitude: 3.5, longitude: 11.35 },
  { name: 'Yerevan', country: { code: 'AM', name: 'Armenia' }, latitude: 40.1, longitude: 44.31 },
  { name: 'Zagreb', country: { code: 'HR', name: 'Croatia' }, latitude: 45.5, longitude: 15.58 },
];
