export const tabsContentStyles = [
  'grow',
  'font-normal',
  'text-sm',
  'p-3',
  'focus:outline-none',
  'focus-visible:rounded-none',
  'focus-visible:ring-2',
  'focus-visible:ring-blue-9',
  'focus-visible:ring-inset',
];

export const tabsListStyles = [
  'hide-scrollbar',
  'flex',
  'border-gray-6',
  'focus:outline-none',
  'focus:ring-0',
  'data-[orientation=horizontal]:h-11',
  'data-[orientation=horizontal]:items-center',
  'data-[orientation=horizontal]:border-b',
  'data-[orientation=horizontal]:gap-2',
  'data-[orientation=horizontal]:overflow-x-scroll',
  'data-[orientation=horizontal]:overflow-y-hidden',
  'data-[orientation=vertical]:py-2',
  'data-[orientation=vertical]:items-start',
  'data-[orientation=vertical]:flex-col',
  'data-[orientation=vertical]:border-r',
  'data-[orientation=vertical]:gap-1',
  'data-[orientation=vertical]:overflow-x-hidden',
  'data-[orientation=vertical]:overflow-y-scroll',
];

export const tabsTriggerContentStyles = [
  'h-7',
  'px-3',
  'flex',
  'items-center',
  'justify-center',
  'gap-1.5',
  'rounded',
  'transition-colors',
  'whitespace-nowrap',
  'group-hover:bg-gray-4',
  'group-focus:text-gray-12',
  'group-focus:bg-gray-4',
  'group-focus-visible:h-8',
  'group-focus-visible:ring-2',
  'group-focus-visible:ring-inset',
  'group-focus-visible:ring-blue-9',
  'group-disabled:cursor-not-allowed',
  'group-disabled:bg-gray-9',
  'group-disabled:hover:bg-gray-9',
  'group-data-[orientation=vertical]:w-full',
  'group-data-[orientation=vertical]:group-focus-visible:h-7',
  'group-data-[orientation=vertical]:group-data-[state=active]:bg-gray-5',
];

export const tabsTriggerIconStyles = [
  'flex',
  'items-center',
  'justify-center',
  'w-4',
  'h-4',
  'text-gray-11',
];

export const tabsTriggerLinkStyles = ['focus:outline-none', 'focus-visible:ring-0'];

export const tabsTriggerStatStyles = [
  'text-gray-11',
  'transition-colors',
  'group-hover:text-gray-12',
  'group-hover:bg-gray-7',
  'group-focus:bg-gray-7',
  'group-focus:text-gray-12',
  'group-data-[state=active]:text-gray-12',
  'group-disabled:bg-gray-10',
  'group-disabled:text-gray-11',
  'group-disabled:hover:text-gray-11',
  'group-disabled:hover:bg-gray-10',
  'group-data-[orientation=vertical]:group-data-[state=active]:bg-gray-7',
  'group-data-[orientation=vertical]:group-data-[state=active]:text-gray-12',
];

export const tabsTriggerStyles = [
  'group',
  'flex',
  'items-center',
  'justify-center',
  'relative',
  'text-sm',
  'gap-1.5',
  'font-medium',
  'transition-colors',
  'text-gray-11',
  'disabled:text-gray-11',
  'disabled:hover:text-gray-11',
  'hover:text-gray-12',
  'focus:outline-none',
  'focus-visible:ring-0',
  'data-[orientation=horizontal]:h-11',
  'data-[orientation=horizontal]:data-[state=active]:text-gray-12',
  'data-[orientation=horizontal]:data-[state=active]:before:absolute',
  'data-[orientation=horizontal]:data-[state=active]:before:bg-gray-9',
  'data-[orientation=horizontal]:data-[state=active]:before:w-full',
  'data-[orientation=horizontal]:data-[state=active]:before:h-0.5',
  'data-[orientation=horizontal]:data-[state=active]:before:rounded-full',
  'data-[orientation=horizontal]:data-[state=active]:before:bottom-[0.75px]',
  'data-[orientation=horizontal]:data-[state=a  ctive]:before:left-0',
  'data-[orientation=vertical]:w-full',
  'data-[orientation=vertical]:px-2',
  'data-[orientation=vertical]:data-[state=active]:text-gray-12',
  'data-[orientation=vertical]:data-[state=active]:before:absolute',
  'data-[orientation=vertical]:data-[state=active]:before:bg-gray-9',
  'data-[orientation=vertical]:data-[state=active]:before:w-0.5',
  'data-[orientation=vertical]:data-[state=active]:before:h-full',
  'data-[orientation=vertical]:data-[state=active]:before:rounded-full',
  'data-[orientation=vertical]:data-[state=active]:before:left-0',
  'data-[orientation=vertical]:data-[state=active]:before:top-0',
];
